app = "amv-livraplus-api"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "4000"

[[services]]
  protocol = "tcp"
  internal_port = 4000
  [[services.ports]]
    port = "80"
    handlers = ["http"]
  [[services.ports]]
    port = "443"
    handlers = ["tls", "http"]
